language: cpp

compiler:
    - clang

script:
    - make tests


notifications:
	email:
        recipients:
            - ym1834@nyu.edu
			- mz2325@nyu.edu
        on_success: always
        on_failure: never
