language: cpp

compiler:
    - clang

script:
    - make tests

notifications:
    email:
        recipients:
            - mz2325@nyu.edu
            - ym1834@nyu.edu
        on_success: always
        on_failure: never
